---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# GOTeDNA
## An R package for guidance on optimal eDNA sampling periods to develop, optimize, and interpret monitoring programs

<!-- badges: start -->
<!-- badges: end -->

The goal of GOTeDNA is to import and format eDNA qPCR and metabarcoding metadata/data from GOTeDNA sample templates, visualize species detection periods, and statistically delineate optimal species detection windows.


## Installation

### non-R users

#### Install R 

We recommend to use R and RStudio: https://posit.co/download/rstudio-desktop/

1. Download R for your OS: https://cran.rstudio.com/

2. Install R Studio


#### Install the package 

You first need to have access to the archive `GoteDNA_{version}.tar.gz`.
Once you have obtained the archive, use the following: 

```R
install.packages("path/to/GoteDNA_{version}.tar.gz")
```





### R users with access to the GitHub repository

You can install the development version of GOTeDNA from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("mkmor/GOTeDNA")
```

## Usage

### R function categories:
- Import data
- Clean/tidy data
- Visualization

```{R}
library("GOTeDNA")
```


### Clean/tidy data

```{R}
newprob <- calc_det_prob(data = D_mb_ex)
scaledprobs <- scale_newprob(D_mb_ex, newprob)
win <- calc_window(
  data = D_mb_ex, threshold = "90", species.name = "Acartia longiremis",scaledprobs
)
```


### Heat map 

```{R hm}
hm_fig(
   taxon.level = "class", taxon.name = "Copepoda", scaledprobs)
```

### Effort needed

```{R effort}
effort_needed_fig(
  scaledprobs$Pscaled_month |> dplyr::filter(
      species %in% "Acartia hudsonica",
      primer == "COI1"
  )
)
```
ecodistrict.select = "Scotian Shelf",
### Sampling effort

```{R higher}
higher_tax_fig(
  data = D_mb_ex |> dplyr::filter(target_subfragment == "COI1"), 
  higher.taxon.select = "phylum", 
  taxon.name = "Bryozoa",
  view.by.level = "genus"
)
```

### Sample size 

```{R sample_size}
sample_size_fig(
  data = D_mb_ex |> dplyr::filter(scientificName == "Acartia hudsonica"),
  species.name = "Acartia hudsonica"
)
```

### Species monthly detection

```{R smooth}
D_mb_ex_slc <- D_mb_ex |>
  dplyr::filter(
    scientificName == "Acartia longiremis",
    target_subfragment == "COI1"
  )
smooth_fig(
  data = D_mb_ex_slc, 
  species.name = "Acartia longiremis"
)
```


### Monthly detection probabilities

```{R thresh_fig}
thresh_fig(taxon.level = "species", taxon.name = "Acartia hudsonica", 
  threshold = "75", scaledprobs)
```


### Shiny 

Once the package loaded, the shiny can be launched using the following function.

```R
run_gotedna_app()
```

There is also a docker file available: 

```sh
# build the container 
docker build -t gotedna . 
# use the container
docker run -it --rm --network host gotedna 
# the shiny will be available at http://0.0.0.0:9292
```